### ISSUE TITLE
Support custom attributes on node

### ISSUE THREAD

**Issue by QubitPi** [paion-data/aristotle#23]
I'm assuming that at this moment there can only be 2 attributes for each node:

1. title
2. description

In our application, which you will be able to see its UI pretty soon, we have lots of data on every single node. For example, one of the node in our database has more than 30 properties.

__We should allow user to freely specify the node properties__. We can assume they are all key-value pairs, such as

```
"name": "..."
"color": "red"
"size": "big"
"location": "(234, 566)"
...
```

**Comment by Doom9527** [comment]
I deside removing the `Title` and `Description` and giving a `Map` to store multiple data values.

**Comment by QubitPi** [comment]
> I deside removing the `Title` and `Description` and giving a `Map` to store multiple data values.

That shall work. One question though: do we assume the map value to be primitive or object?

**Comment by Doom9527** [comment]
> > I deside removing the `Title` and `Description` and giving a `Map` to store multiple data values.
> 
> That shall work. One question though: do we assume the map value to be primitive or object?

I'm going to use the `String` directly, and some potentially complex data will be serialized back to `String`

**Comment by QubitPi** [comment]
> > > I deside removing the `Title` and `Description` and giving a `Map` to store multiple data values.
> > 
> > 
> > That shall work. One question though: do we assume the map value to be primitive or object?
> 
> I'm going to use the `String` directly, and some potentially complex data will be serialized back to `String`.

String would be OK at this moment. In fact, do do with String in this PR, because this will be the first step for [later improvement](https://github.com/paion-data/aristotle/issues/30)
